### ISSUE TITLE
It is unclear how to compare two files (that exist outside of a solution)

### ISSUE THREAD

**Issue by daiplusplus** [madskristensen/FileDiffer#22] opened 2017-12-06 03:02 UTC
### Installed product versions
- Visual Studio: 2017 Enterprise 15.4.5
- This extension: 1.4.24

### Description
I want to compare/diff two files that I have saved on my desktop, but I can't see any menu item to compare two files - only the Solution explorer context-menu option to compare a solution item with another file.

### Expected behavior
I'd like to see a "Compare files..." option on the main Visual Studio File or Tools menu which would open two Open File Dialog prompts to select the two files to compare.

**Comment by Netstep** [comment] 2018-10-05 06:35
Seems it doesn't work in folders mode, only in solution mode

**Comment by borysr** [comment] 2018-12-05 14:49
Can this be added to the folder mode and may be, "compare open files "?

**Comment by Trevor89** [comment] 2020-04-15 16:01
Ah, ok, my issue is answered and so Ill add my vote to this too

Trev

**Comment by daiplusplus** [comment] 2020-05-14 22:03
> **Netstep** Seems it doesn't work in folders mode, only in solution mode

In addition to Folders Mode, I'd like it to also work when VS doesn't have any Solution or Folder open at all - e.g. from the Start Page or from an Empty environment. It sucks that Microsoft removed `windiff.exe` from the Windows 10 SDK - so I've been using web-based diffing websites like https://www.diffchecker.com/ - but this doesn't work well when I'm working with large files or files that I'd like syntax highlighting for, or when those files contain secret/confidential information that I don't want to post to an untrusted website/

**Comment by madskristensen** [comment] 2020-07-16 22:20
Duplicate of #20

**Closed as completed by madskristensen** 2020-07-16 22:20 UTC
